<!doctype html>
<html>
<head>
<?php echo $gi->echo_js_libs('../../../'); ?>
<script type='text/javascript'>
  google.load("identitytoolkit", "2", {
    packages: [ "ac"],
    language: "en"
  });
</script>
<script>
$(function() {
 window.google.identitytoolkit.setConfig({
    developerKey: "<?php echo $conf->get('developerKey'); ?>",
    companyName: "<?php echo $conf->get('companyName'); ?>",
    callbackUrl: "<?php echo $conf->get('callbackUrl'); ?>",
    realm: "",
    userStatusUrl: "/gi/statusUrl",
    loginUrl: "/gi/login",
    signupUrl:"/gi/signup",
    homeUrl:  "/gi/home",
    logoutUrl: "/gi/logout",
    idps: ["Gmail", "Yahoo"],
    idpConfig: {
        Gmail: {
          scopes: [
            "https://www.googleapis.com/auth/plus.me"
                   ],
        }
      },
    tryFederatedFirst: true,
    language: 'en',
    useContextParam: true,
    useCachedUserStatus: true,
   });
});
  var conf = window.graphit.auth;
  console.log('graphit', window.graphit);
  <?php
/* Feed our Javascript Object */
if ($gi->get('verifiedEmail')) {
	echo $gi->js_fill_conf();
}
  ?>
  var userData = {};
  <?php if ($gi->get('verifiedEmail')) : ?>
   userData = {
        email: conf.get("verifiedEmail"),
        displayName: conf.get("displayName"),
        photoUrl: conf.get("photoUrl")
    };
  <?php endif; ?>
  var o = window.opener;
  if (o) {
  o.google.identitytoolkit.updateSavedAccount(userData);
  console.log('userData', userData);
  o.graphit.auth.send_trigger('update');
  window.close();
  }
  </script>
</head>
<script
</script>
<body>
</body>
</html>
